### ISSUE TITLE
Should we port older write-ups?

### ISSUE THREAD

**Issue by avlidienbrunn** [cure53/XSSChallengeWiki#1]
The [Older-Challenges-and-Write-Ups](https://github.com/cure53/xss-challenge-wiki/wiki/Older-Challenges-and-Write-Ups) page has links to write-ups for some of the older challenges. However, I think it would be nice to get the write-ups in the same wiki format, so maybe we could port the older write-ups (while of course linking to them etc).

Another benefit of this is that the techniques doesn't go lost if the respective write-up is taken offline. I didn't want to start porting before I got you other people's opinion. What do you guys think?

**Comment by ohpe** [comment]
Sure we'll port every challenge in the wiki format, it's a matter of time :)
We started with prompt.ml in order to have a "template" of the wiki but for me, and I think it's the same for @cure53, that list is just a reminder of what's next challenge to "port" in the wiki list.

**Comment by cure53** [comment]
Agreed, once we have the time we just gradually add what we find

**Comment by cure53** [comment]
I ported the Cure53 X-Mas '13 challenge. Any other larger challenges we should create dedicated pages for?

**Comment by filedescriptor** [comment]
I think that's it :) One thing I'm not sure about is how we determine whether a challenge should have its dedicated page(even for future challenges?)

**Comment by cure53** [comment]
That is a good question. From my personal perspective, I'd add challenge write-ups of challenge I participated in. For anything else.. pull requests welcome? :)

**Comment by filedescriptor** [comment]
Fine :)
