### ISSUE TITLE
incorrect event name oppopstate in XSSMAS 2015

### ISSUE THREAD

**Issue by emanuelb** [cure53/XSSChallengeWiki#10]
in $events array at:
https://github.com/cure53/XSSChallengeWiki/wiki/XSSMas-Challenge-2015
there is incorrect event name:
```
	    'oppopstate',
```
instead of the correct event name:
```
	    'onpopstate',
```
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate

**Comment by cure53** [comment]
Fixed, thx :)
