### ISSUE TITLE
Were the changes of prompt.ml write-up reverted?

### ISSUE THREAD

**Issue by filedescriptor** [cure53/XSSChallengeWiki#2]
https://github.com/cure53/xss-challenge-wiki/wiki/prompt.ml/_compare/8e398ad0d36deb9eba95355f07e1a1444324202a...6fca4e9a6e6b8fa69742a28db6ed0478516e98d9

It seems some changes were reverted. Is that a mistake?

**Comment by cure53** [comment]
I did some layout and language fixes and tried to resolve a conflict. If
anything valuable was killed during this process: sorry - not intended.
Feel free to fix today, I'll be mostly off-line ;)

**Comment by filedescriptor** [comment]
Alas, It was somehow fixed. Maybe I overlooked something, thanks :)
