### ISSUE TITLE
Are we ready for publication? If so please "+1"

### ISSUE THREAD

**Issue by cure53** [cure53/XSSChallengeWiki#3]
I think we are close to be ready. If you think so too please comment real quick with a "+1" or "-1". Thanks!

**Comment by filedescriptor** [comment]
-1

**Comment by cure53** [comment]
Aye, what's still missing?

**Comment by ohpe** [comment]
:-1:  the Level 11 is missing

**Comment by filedescriptor** [comment]
I think the explanation of some levels are not thorough enough, some are even not correct :( Too bad I don't have time to correct them.

**Comment by cure53** [comment]
Okay then let's wait of course. I have zero time this week and won't edit, so no more collisions.

**Comment by cure53** [comment]
Gentlemen, what is missing for publication? I have some time this week and can do some changes.

**Comment by filedescriptor** [comment]
I think we are okay for publication now. Only slight formatting & languages fixes & whatnot needed before publishing :)

**Comment by cure53** [comment]
Okay, cool. You wanna have a look first? Or you have specifics to check?

**Comment by filedescriptor** [comment]
I just feel like there may be minor mistakes. Anyways we can publish it first and then fix them? People must be waiting for it so hard :+1:

**Comment by cure53** [comment]
+1 From my side. @ohpe @crypto @avlidienbrunn @rafaybaloch What say yee?

**Comment by ohpe** [comment]
Ehm Level 11 doesn't have the introduction, after that I think it's :+1:

**Comment by cure53** [comment]
I'll add one now.

**Comment by rafaybaloch** [comment]
+1

On Wed, Sep 17, 2014 at 3:29 PM, Cure53 notifications@github.com wrote:

> I'll add one now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cure53/xss-challenge-wiki/issues/3#issuecomment-55875731
> .

## 

Warm Regards,
Rafay Baloch

http://rafayhackingarticles.net
http://techlotips.com

**Comment by filedescriptor** [comment]
Since it's published I am going to close this.
