### ISSUE TITLE
Should we have a spoiler alert sign on write-ups?

### ISSUE THREAD

**Issue by filedescriptor** [cure53/XSSChallengeWiki#5]
I think it could be better if we can add it on every write-up, as some people may just want to solve it themselves first (I mean, the challenge link is inside the write-up).

I'm not familiar with Github wiki, but I think the ideal way to do it is to place a prompt message to make sure if one really wants to read the write-up, if not feasible we can just put up a header section.

Thoughts?

**Comment by ohpe** [comment]
I think that the prompt message is too "extreme" and not feasible but a warning message in the header or also a picture would be fine. :+1:

**Comment by cure53** [comment]
Hm, I think the whole purpose of the wiki is to document solutions. So the spoiler effect is kinda unavoidable and hopefully expected by the readers. 

Maybe some warning in bold letters on the index page?

**Comment by filedescriptor** [comment]
Yes, I think at least emphasis is needed, as someone may not aware of it.

The other thing I'm talking about is that one is unavoidably "spoilered" while one wants to try it first.
For example, If I am new to challenges and want to try Puzzle 1 on kcal.pw, I will have to go [here](https://github.com/cure53/xss-challenge-wiki/wiki/Puzzle-1-on-kcal.pw) to grab the link - and being "spoilered" at the same time.

**Comment by cure53** [comment]
I changed the text on the index page, what do you think? 

https://github.com/cure53/xss-challenge-wiki/wiki

**Comment by filedescriptor** [comment]
Great!
