### ISSUE TITLE
ellEnable Sourcegraph

### ISSUE THREAD

**Issue by makwanakalpesh1** [cure53/XSSChallengeWiki#6]
I want to use [Sourcegraph](https://sourcegraph.com) for xss-challenge-wiki code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/cure53/xss-challenge-wiki. (It should only take 30 seconds.)

Thank you!

**Comment by cure53** [comment]
Heya, basically no problem but I am not happy with the required permissions Sourcegraph is asking for. So the best would be to just fork and allow Sourcegraph for your version. Sounds okay?
