### ISSUE TITLE
Level-8___can't figure out with vector in writeup

### ISSUE THREAD

**Issue by a1exlism** [cure53/XSSChallengeWiki#8]
In [Level-8](http://prompt.ml/8), the writeup themes doesn't work.

my local test is down below:
1. this works well

``` html
<script>
    //  console.log("
        alert(1)<!--");
    </script>
```
1.  this doesn't work.

``` html
<script>
    //  console.log("
        alert(1)-->");
    </script>
```

and I can't bypass the **Line Break**(with [U+2028]), anyone can help?

**Comment by cure53** [comment]
Which browser did you try?

**Comment by cure53** [comment]
Also, try to grab the u+2029 from here, between "copy" and "me" :) http://pastebin.com/QKbiVU8z

**Comment by a1exlism** [comment]
My browser is **53.0.2785.46 (Official Build) beta (64-bit)** . And I tried your codes in pasetbin and it works! But **[u+2029]  \u2029 [u+2029]  \u2028** still not work well in my browser(chrome & Mozilla Firefox 48.0).

**Comment by cure53** [comment]
I tested and it works for me. Both on latest FF and Chrome.

**Comment by a1exlism** [comment]
sry, I made a mistakes in comprehension..  The vector works well.

**Comment by sA74n** [comment]
it is working when i copied the result of `&#x2029;prompt(1);&#x2029;-->` in html context and pasted it in input of https://prompt.ml/8
