### ISSUE TITLE
Level 8 Solution is not working in any modern browser

### ISSUE THREAD

**Issue by caglarsayin** [cure53/XSSChallengeWiki#9]
I tried to replay solution 8 on prompt.ml with latest chrome, firefox and safari. Did not reproduce the prompt(1) output. 

Can you please review it?

**Comment by ohpe** [comment]
It works. Maybe you're missing the separators. 
Try to run the following code in your browser console:
```js
console.log("\u2028prompt(1)\u2028-->")
```
then copy the entire row output and paste in the challenge.

**Comment by cure53** [comment]
Yep, that should do it. Thx @ohpe!

**Comment by mathiasbynens** [comment]
In the Chromium DevTools, you can use `copy('\u2028prompt(1)\u2028-->')`.

**Comment by sA74n** [comment]
i tried this in my browser as a solution for level 8
 `console.log("\u2028prompt(1)\u2028-->")`, 
but its not working now?
